"""`jobpipe init` — interactive first-run setup.

Asks a dozen questions and generates config/profile.yaml and
config/answers.yaml from the bundled *.example.yaml templates.

The generated files intentionally drop the templates' inline comments
(yaml.safe_dump can't preserve them) — the example files stay in the repo
as the documented reference, so a header comment in each generated file
points back at them.
"""

from __future__ import annotations

import sys

import yaml

from .config import ANSWERS_PATH, CONFIG_DIR, PROFILE_PATH, clear_caches

GENERATED_HEADER = (
    "# Generated by `python jobpipe.py init`.\n"
    "# Every field is documented in config/{example}.\n"
    "# Copy sections from there whenever you want to tune scoring; then run\n"
    "# `python jobpipe.py rescore` to apply changes.\n\n"
)


def ask(prompt: str, default: str = "") -> str:
    """EOF-safe input() so the whole wizard can be piped non-interactively."""
    suffix = f" [{default}]" if default else ""
    try:
        val = input(f"{prompt}{suffix}: ").strip()
    except EOFError:
        val = ""
    return val or default


def ask_bool(prompt: str, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    val = ask(f"{prompt} ({hint})")
    if not val:
        return default
    return val.lower().startswith("y")


def _csv(raw: str) -> list[str]:
    return [t.strip().lower() for t in raw.split(",") if t.strip()]


def _load_template(name: str) -> dict:
    path = CONFIG_DIR / name
    if not path.exists():
        raise SystemExit(f"Template missing: {path} — is the repo checkout complete?")
    with open(path) as f:
        return yaml.safe_load(f)


def _write(path, data: dict, example: str) -> None:
    with open(path, "w") as f:
        f.write(GENERATED_HEADER.format(example=example))
        yaml.safe_dump(data, f, sort_keys=False, allow_unicode=True, width=100)
    print(f"  ✓ wrote {path}")


def _confirm_overwrite(path, force: bool) -> bool:
    if force or not path.exists():
        return True
    return ask_bool(f"{path.name} already exists — overwrite it?", default=False)


def run(force: bool = False) -> None:
    print("jobpipe setup — press Enter to accept a default, comma-separate lists.\n")

    write_profile = _confirm_overwrite(PROFILE_PATH, force)
    write_answers = _confirm_overwrite(ANSWERS_PATH, force)
    if not (write_profile or write_answers):
        print("Nothing to do — both config files kept as they are.")
        return

    # ── shared questions ─────────────────────────────────────────────
    name = ask("Your name (stays in your local config only)", "Jane Doe")
    strong = _csv(ask(
        "Target job titles, comma-separated",
        "data engineer, analytics engineer, data platform engineer"))
    good = _csv(ask(
        "Adjacent titles worth surfacing (lower priority)",
        "machine learning engineer, mlops engineer, platform engineer"))
    try:
        yoe = int(ask("Years of professional experience", "2"))
    except ValueError:
        yoe = 2
    cities = _csv(ask("Preferred cities/metros, comma-separated", "new york, nyc, brooklyn"))
    want_remote = ask_bool("Include remote-US roles?", default=True)
    needs_sponsor = ask_bool("Do you need visa sponsorship (e.g. H-1B)?", default=True)
    stack = _csv(ask("Your strongest tools/technologies", "python, sql, airflow, spark"))
    try:
        daily = int(ask("Daily shortlist size", "8"))
    except ValueError:
        daily = 8
    print("\nLLM enrichment backend:\n"
          "  auto — use the Anthropic API when a key is set, else Claude Code, else skip\n"
          "  api  — Anthropic API only (needs ANTHROPIC_API_KEY; metered billing)\n"
          "  cc   — Claude Code headless only (subscription quota)\n"
          "  off  — disable LLM enrichment entirely")
    backend = ask("Backend", "auto").lower()
    if backend not in ("auto", "api", "cc", "off"):
        backend = "auto"

    if write_profile:
        p = _load_template("profile.example.yaml")
        cand = p.setdefault("candidate", {})
        cand["name"] = name
        cand["years_experience"] = yoe
        cand["needs_sponsorship"] = needs_sponsor
        cand["targets"] = [t.title() for t in strong]
        if not needs_sponsor:
            cand["visa"] = "authorized to work in the US, no sponsorship needed"

        p.setdefault("titles", {})
        p["titles"]["strong"] = strong
        p["titles"]["good"] = good

        # Derive the YoE curve from the answer: full bonus at your own level,
        # tapering penalties above it; hard reject well out of reach.
        y = max(1, yoe)
        p.setdefault("yoe", {})
        p["yoe"]["bonus"] = {y: 18, y + 1: -4, y + 2: -10, y + 3: -16, y + 5: -20}
        p["yoe"]["reject_at"] = max(8, y + 6)

        tiers = p.setdefault("locations", {}).get("tiers") or []
        if cities:
            preferred = {"name": "preferred", "points": 14, "us_anchor": True,
                         "match": cities}
            tiers = [preferred] + [t for t in tiers
                                   if t.get("name") not in ("nyc", "preferred")]
        if not want_remote:
            tiers = [t for t in tiers if t.get("name") != "remote"]
        p["locations"]["tiers"] = tiers

        kws = p.setdefault("keywords", {})
        for t in stack:
            kws.setdefault(t, 5)

        if not needs_sponsor:
            # Sponsorship signals are irrelevant — neutralize the bonus map and
            # let every sponsor status through the golden gate.
            p["sponsor_history_bonus"] = {k: 0 for k in
                                          (p.get("sponsor_history_bonus") or {})}
            if "golden" in p:
                p["golden"]["sponsor"] = ["heavy", "yes", "positive", "low",
                                          "unknown", "none"]

        p.setdefault("thresholds", {})["daily_shortlist_size"] = daily

        llm = p.setdefault("llm", {})
        if backend == "off":
            llm["enabled"] = False
        else:
            llm["enabled"] = True
            llm["backend"] = backend

        _write(PROFILE_PATH, p, "profile.example.yaml")

    if write_answers:
        a = _load_template("answers.example.yaml")
        ident = a.setdefault("identity", {})
        parts = name.split()
        ident["first_name"] = parts[0] if parts else ""
        ident["last_name"] = " ".join(parts[1:]) if len(parts) > 1 else ""
        email = ask("Email (Enter to skip)")
        if email:
            ident["email"] = email
        phone = ask("Phone (Enter to skip)")
        if phone:
            ident["phone"] = phone
        loc = ask("City, State (Enter to skip)")
        if loc:
            ident["location"] = loc
        linkedin = ask("LinkedIn URL (Enter to skip)")
        if linkedin:
            ident["linkedin"] = linkedin
        auth = ask('Work authorization (e.g. "F-1 OPT", "US Citizen"; Enter to skip)')
        if auth:
            ident["work_auth"] = auth
        ident["visa_sponsorship_needed"] = needs_sponsor
        for item in a.get("standard") or []:
            if "sponsorship" in item.get("q", "").lower():
                item["a"] = ("Yes, I will require sponsorship in the future."
                             if needs_sponsor else
                             "No, I will not require sponsorship.")
        _write(ANSWERS_PATH, a, "answers.example.yaml")

    clear_caches()
    print("\nDone. Next steps:\n"
          "  python jobpipe.py verify     # probe the ATS tokens in config/companies.yaml\n"
          "  python jobpipe.py fetch      # scrape all boards and score everything\n"
          "  python jobpipe.py shortlist  # your daily list\n"
          "  python board/app.py          # web board on http://127.0.0.1:5175\n")
    sys.stdout.flush()
